function [fitresult, gof] = fit_gauss_2d_2term_bg(x, y, gfp)
%CREATEFIT(X,Y,GFP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: gfp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Apr-2021 10:56:43


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x, y, gfp );

% Set up fittype and options.
ft = fittype( 'a1*exp(-((x-mu1_x)^2/(2*sig1_x^2) + (y-mu1_y)^2/(2*sig1_y^2))) + a2*exp(-((x-mu2_x)^2/(2*sig2_x^2) + (y-mu2_y)^2/(2*sig2_y^2))) + bg;', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 0 0.3 0.3 0.3 0.3];
opts.StartPoint = [49342 49342 15503 8 9.5 8 9.5 0.6 0.6 0.6 0.6];
opts.Upper = [493420 493420 25000 16 19 16 19 1.2 1.2 1.2 1.2];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'gfp vs. x, y', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
zlabel( 'Intensity (AU)', 'Interpreter', 'none' );
grid on
view( -136.9, 35.1 );


